# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16fzbFXPXK-n9dK5yCv4PmOWv-ytxKC06
"""

# ============================================================================
# AADHAAR BIOMETRIC ANALYSIS - MODEL TRAINING & EXPORT
# Complete ML Pipeline with Model Saving for Web Deployment
# ============================================================================

# Install required libraries
!pip install plotly folium scikit-learn pandas numpy matplotlib seaborn prophet joblib flask -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, GradientBoostingClassifier, IsolationForest
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import mean_squared_error, r2_score, classification_report, roc_auc_score, roc_curve
import joblib
from datetime import datetime
import json

warnings.filterwarnings('ignore')

print("="*80)
print("AADHAAR BIOMETRIC ANALYSIS - MODEL TRAINING")
print("="*80)

# Load data
from google.colab import files
print("\n📁 Please upload your CSV file:")
uploaded = files.upload()

filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)

print(f"\n✅ Data loaded successfully!")
print(f"Shape: {df.shape}")
print(f"\nColumns: {list(df.columns)}")

# Convert date to datetime
df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')

# Feature Engineering
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['total_bio'] = df['bio_age_5_17'] + df['bio_age_17_']
df['pct_children'] = (df['bio_age_5_17'] / df['total_bio'] * 100).fillna(0)
df['pct_adults'] = (df['bio_age_17_'] / df['total_bio'] * 100).fillna(0)

print(f"\n✅ Feature engineering complete!")

print("\n" + "="*80)
print("MODEL 1: ENROLLMENT VOLUME PREDICTION (REGRESSION)")
print("="*80)

# Encode categorical features
le = LabelEncoder()
df['state_encoded'] = le.fit_transform(df['state'])
df['district_encoded'] = le.fit_transform(df['district'])

# Prepare features for regression
features_reg = ['state_encoded', 'district_encoded', 'month', 'day', 'pct_children', 'pct_adults']
X_reg = df[features_reg]
y_children = df['bio_age_5_17']
y_adults = df['bio_age_17_']

# Split data
X_train_reg, X_test_reg, y_train_c, y_test_c = train_test_split(
    X_reg, y_children, test_size=0.2, random_state=42
)
_, _, y_train_a, y_test_a = train_test_split(
    X_reg, y_adults, test_size=0.2, random_state=42
)

# Train Random Forest for Children
print("\n🔄 Training Children Enrollment Model...")
rf_children = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1, max_depth=10)
rf_children.fit(X_train_reg, y_train_c)
pred_c = rf_children.predict(X_test_reg)

print(f"✅ Children Model - R² Score: {r2_score(y_test_c, pred_c):.4f}")
print(f"   RMSE: {np.sqrt(mean_squared_error(y_test_c, pred_c)):.4f}")

# Train Random Forest for Adults
print("\n🔄 Training Adult Enrollment Model...")
rf_adults = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1, max_depth=10)
rf_adults.fit(X_train_reg, y_train_a)
pred_a = rf_adults.predict(X_test_reg)

print(f"✅ Adult Model - R² Score: {r2_score(y_test_a, pred_a):.4f}")
print(f"   RMSE: {np.sqrt(mean_squared_error(y_test_a, pred_a)):.4f}")

print("\n" + "="*80)
print("MODEL 2: ENROLLMENT PROBABILITY CLASSIFICATION")
print("="*80)

# Create binary target
median_enrollment = df['total_bio'].median()
df['high_enrollment'] = (df['total_bio'] > median_enrollment).astype(int)

X_class = df[features_reg]
y_class = df['high_enrollment']

# Scale features
scaler_class = StandardScaler()
X_class_scaled = scaler_class.fit_transform(X_class)

# Split data
X_train_c, X_test_c, y_train_cl, y_test_cl = train_test_split(
    X_class_scaled, y_class, test_size=0.2, random_state=42, stratify=y_class
)

# Train Gradient Boosting Classifier
print("\n🔄 Training Classification Model...")
gb_classifier = GradientBoostingClassifier(n_estimators=100, random_state=42, max_depth=5)
gb_classifier.fit(X_train_c, y_train_cl)

y_pred_prob = gb_classifier.predict_proba(X_test_c)[:, 1]
y_pred_class = gb_classifier.predict(X_test_c)

print(f"\n✅ Classification Model Performance:")
print(f"   ROC-AUC Score: {roc_auc_score(y_test_cl, y_pred_prob):.4f}")
print(f"   Accuracy: {(y_pred_class == y_test_cl).mean():.4f}")

print("\n" + "="*80)
print("MODEL 3: ANOMALY DETECTION")
print("="*80)

# Prepare features for anomaly detection
X_anomaly = df[['bio_age_5_17', 'bio_age_17_', 'total_bio', 'pct_children']]

# Train Isolation Forest
print("\n🔄 Training Anomaly Detection Model...")
iso_forest = IsolationForest(contamination=0.1, random_state=42, n_estimators=100)
iso_forest.fit(X_anomaly)

df['anomaly'] = iso_forest.predict(X_anomaly)
df['anomaly_score'] = iso_forest.score_samples(X_anomaly)

anomalies = df[df['anomaly'] == -1]
print(f"\n✅ Anomalies detected: {len(anomalies)} out of {len(df)} records ({len(anomalies)/len(df)*100:.2f}%)")

print("\n" + "="*80)
print("MODEL 4: REGION CLUSTERING")
print("="*80)

# Prepare features for clustering
X_cluster = df[['bio_age_5_17', 'bio_age_17_', 'total_bio', 'pct_children']]
scaler_cluster = StandardScaler()
X_cluster_scaled = scaler_cluster.fit_transform(X_cluster)

# Train K-Means
optimal_k = 4
print(f"\n🔄 Training K-Means Clustering (k={optimal_k})...")
kmeans = KMeans(n_clusters=optimal_k, random_state=42, n_init=10)
df['cluster'] = kmeans.fit_predict(X_cluster_scaled)

print(f"✅ Regions clustered into {optimal_k} groups")

# Cluster characteristics
cluster_summary = df.groupby('cluster').agg({
    'bio_age_5_17': 'mean',
    'bio_age_17_': 'mean',
    'total_bio': 'mean',
    'pincode': 'count'
}).round(2)
print("\nCluster Characteristics:")
print(cluster_summary)

print("\n" + "="*80)
print("SAVING MODELS FOR WEB DEPLOYMENT")
print("="*80)

# Create models directory
!mkdir -p models

# Save all models
print("\n💾 Saving models...")

joblib.dump(rf_children, 'models/rf_children_model.pkl')
joblib.dump(rf_adults, 'models/rf_adults_model.pkl')
joblib.dump(gb_classifier, 'models/gb_classifier_model.pkl')
joblib.dump(iso_forest, 'models/isolation_forest_model.pkl')
joblib.dump(kmeans, 'models/kmeans_model.pkl')

# Save scalers
joblib.dump(scaler_class, 'models/scaler_classification.pkl')
joblib.dump(scaler_cluster, 'models/scaler_clustering.pkl')

# Save encoders
joblib.dump(le_state, 'models/label_encoder_state.pkl')
joblib.dump(le_district, 'models/label_encoder_district.pkl')

# Save feature names
feature_info = {
    'regression_features': features_reg,
    'states': le_state.classes_.tolist(),
    'districts': le_district.classes_.tolist(),
    'optimal_clusters': optimal_k,
    'median_enrollment': float(median_enrollment)
}

with open('models/feature_info.json', 'w') as f:
    json.dump(feature_info, f, indent=2)

print("✅ All models saved successfully!")
print("\nSaved files:")
print("  - rf_children_model.pkl (Children enrollment predictor)")
print("  - rf_adults_model.pkl (Adult enrollment predictor)")
print("  - gb_classifier_model.pkl (High/Low enrollment classifier)")
print("  - isolation_forest_model.pkl (Anomaly detector)")
print("  - kmeans_model.pkl (Region clustering)")
print("  - scaler_classification.pkl (Feature scaler for classification)")
print("  - scaler_clustering.pkl (Feature scaler for clustering)")
print("  - label_encoder_state.pkl (State encoder)")
print("  - label_encoder_district.pkl (District encoder)")
print("  - feature_info.json (Feature metadata)")

"""# Task
Modify the 'MODEL 1: ENROLLMENT VOLUME PREDICTION (REGRESSION)' cell to define separate LabelEncoder instances, `le_state` and `le_district`, for encoding 'state' and 'district' columns respectively. After modifying, re-execute the 'MODEL 1: ENROLLMENT VOLUME PREDICTION (REGRESSION)' cell and the 'SAVING MODELS FOR WEB DEPLOYMENT' cell to ensure `le_state` and `le_district` are saved correctly.

## Define separate LabelEncoders

### Subtask:
Modify the 'MODEL 1: ENROLLMENT VOLUME PREDICTION (REGRESSION)' cell to create and use distinct `LabelEncoder` instances for 'state' and 'district' (e.g., `le_state` and `le_district`).

**Reasoning**:
The current code has an error because `le_state` and `le_district` are not defined. To fix this, I need to modify the 'MODEL 1: ENROLLMENT VOLUME PREDICTION (REGRESSION)' cell (cell_id: NVDwOJcAOA7z) to create distinct `LabelEncoder` instances for 'state' and 'district', and then ensure these new instances are used correctly for encoding.
"""

print("\n" + "="*80)
print("MODEL 1: ENROLLMENT VOLUME PREDICTION (REGRESSION)")
print("="*80)

# Encode categorical features
# Create separate LabelEncoder instances for 'state' and 'district'
le_state = LabelEncoder()
le_district = LabelEncoder()
df['state_encoded'] = le_state.fit_transform(df['state'])
df['district_encoded'] = le_district.fit_transform(df['district'])

# Prepare features for regression
features_reg = ['state_encoded', 'district_encoded', 'month', 'day', 'pct_children', 'pct_adults']
X_reg = df[features_reg]
y_children = df['bio_age_5_17']
y_adults = df['bio_age_17_']

# Split data
X_train_reg, X_test_reg, y_train_c, y_test_c = train_test_split(
    X_reg, y_children, test_size=0.2, random_state=42
)
_, _, y_train_a, y_test_a = train_test_split(
    X_reg, y_adults, test_size=0.2, random_state=42
)

# Train Random Forest for Children
print("\n🔄 Training Children Enrollment Model...")
rf_children = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1, max_depth=10)
rf_children.fit(X_train_reg, y_train_c)
pred_c = rf_children.predict(X_test_reg)

print(f"✅ Children Model - R² Score: {r2_score(y_test_c, pred_c):.4f}")
print(f"   RMSE: {np.sqrt(mean_squared_error(y_test_c, pred_c)):.4f}")

# Train Random Forest for Adults
print("\n🔄 Training Adult Enrollment Model...")
rf_adults = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1, max_depth=10)
rf_adults.fit(X_train_reg, y_train_a)
pred_a = rf_adults.predict(X_test_reg)

print(f"✅ Adult Model - R² Score: {r2_score(y_test_a, pred_a):.4f}")
print(f"   RMSE: {np.sqrt(mean_squared_error(y_test_a, pred_a)):.4f}")

"""**Reasoning**:
The previous step successfully modified and re-executed the 'MODEL 1: ENROLLMENT VOLUME PREDICTION (REGRESSION)' cell, creating the `le_state` and `le_district` objects. Now, I need to re-execute the 'SAVING MODELS FOR WEB DEPLOYMENT' cell to ensure these newly defined encoders are properly saved, as instructed by the subtask.


"""

print("\n" + "="*80)
print("SAVING MODELS FOR WEB DEPLOYMENT")
print("="*80)

# Create models directory
!mkdir -p models

# Save all models
print("\n💾 Saving models...")

joblib.dump(rf_children, 'models/rf_children_model.pkl')
joblib.dump(rf_adults, 'models/rf_adults_model.pkl')
joblib.dump(gb_classifier, 'models/gb_classifier_model.pkl')
joblib.dump(iso_forest, 'models/isolation_forest_model.pkl')
joblib.dump(kmeans, 'models/kmeans_model.pkl')

# Save scalers
joblib.dump(scaler_class, 'models/scaler_classification.pkl')
joblib.dump(scaler_cluster, 'models/scaler_clustering.pkl')

# Save encoders
joblib.dump(le_state, 'models/label_encoder_state.pkl')
joblib.dump(le_district, 'models/label_encoder_district.pkl')

# Save feature names
feature_info = {
    'regression_features': features_reg,
    'states': le_state.classes_.tolist(),
    'districts': le_district.classes_.tolist(),
    'optimal_clusters': optimal_k,
    'median_enrollment': float(median_enrollment)
}

with open('models/feature_info.json', 'w') as f:
    json.dump(feature_info, f, indent=2)

print("✅ All models saved successfully!")
print("\nSaved files:")
print("  - rf_children_model.pkl (Children enrollment predictor)")
print("  - rf_adults_model.pkl (Adult enrollment predictor)")
print("  - gb_classifier_model.pkl (High/Low enrollment classifier)")
print("  - isolation_forest_model.pkl (Anomaly detector)")
print("  - kmeans_model.pkl (Region clustering)")
print("  - scaler_classification.pkl (Feature scaler for classification)")
print("  - scaler_clustering.pkl (Feature scaler for clustering)")
print("  - label_encoder_state.pkl (State encoder)")
print("  - label_encoder_district.pkl (District encoder)")
print("  - feature_info.json (Feature metadata)")

print("\n" + "="*80)
print("TESTING MODELS WITH SAMPLE DATA")
print("="*80)

# Create sample test data
sample_data = df.iloc[0:5][features_reg].copy()
print("\n📊 Sample Input Data:")
print(sample_data)

# Test predictions
print("\n🔮 Sample Predictions:")

# Regression predictions
sample_pred_children = rf_children.predict(sample_data)
sample_pred_adults = rf_adults.predict(sample_data)
print("\nChildren Enrollment Predictions:", sample_pred_children.round(2))
print("Adult Enrollment Predictions:", sample_pred_adults.round(2))

# Classification predictions
sample_scaled = scaler_class.transform(sample_data)
sample_class_pred = gb_classifier.predict_proba(sample_scaled)[:, 1]
print("\nHigh Enrollment Probability:", sample_class_pred.round(3))

# Anomaly detection
sample_anomaly = df.iloc[0:5][['bio_age_5_17', 'bio_age_17_', 'total_bio', 'pct_children']]
sample_anomaly_pred = iso_forest.predict(sample_anomaly)
print("\nAnomaly Detection (1=Normal, -1=Anomaly):", sample_anomaly_pred)

# Clustering
sample_cluster_scaled = scaler_cluster.transform(sample_anomaly)
sample_cluster_pred = kmeans.predict(sample_cluster_scaled)
print("\nCluster Assignment:", sample_cluster_pred)

print("\n" + "="*80)
print("DOWNLOADING MODELS")
print("="*80)

# Zip all models
!zip -r models.zip models/

print("\n✅ Models zipped successfully!")
print("\n📥 Downloading models.zip...")

files.download('models.zip')

print("\n🎉 MODEL TRAINING COMPLETE!")
print("\nYou can now use these models in your web application.")
print("Next step: Use the Flask/FastAPI backend code to deploy these models!")

print("\n" + "="*80)
print("GENERATING DASHBOARD STATISTICS")
print("="*80)

# Calculate key metrics
stats = {
    'total_enrollments': int(df['total_bio'].sum()),
    'total_children': int(df['bio_age_5_17'].sum()),
    'total_adults': int(df['bio_age_17_'].sum()),
    'num_states': int(df['state'].nunique()),
    'num_districts': int(df['district'].nunique()),
    'num_pincodes': int(df['pincode'].nunique()),
    'avg_enrollment_per_pincode': float(df['total_bio'].mean()),
    'median_enrollment': float(df['total_bio'].median()),
    'anomaly_percentage': float(len(anomalies) / len(df) * 100),
    'high_enrollment_areas': int((df['high_enrollment'] == 1).sum()),
    'low_enrollment_areas': int((df['high_enrollment'] == 0).sum())
}

# State-wise statistics
state_stats = df.groupby('state').agg({
    'bio_age_5_17': 'sum',
    'bio_age_17_': 'sum',
    'total_bio': 'sum',
    'pincode': 'count'
}).to_dict()

# Save statistics
with open('models/dashboard_stats.json', 'w') as f:
    json.dump({'summary': stats, 'state_stats': state_stats}, f, indent=2)

print("✅ Dashboard statistics saved!")
print("\nKey Metrics:")
for key, value in stats.items():
    print(f"  - {key}: {value}")

print("\n" + "="*80)
print("ALL DONE! Ready for web deployment 🚀")
print("="*80)

"""## Summary:

### Data Analysis Key Findings

*   The `MODEL 1: ENROLLMENT VOLUME PREDICTION (REGRESSION)` cell was modified to use separate `LabelEncoder` instances: `le_state` for the 'state' column and `le_district` for the 'district' column.
*   After the modification, the Children Enrollment Model achieved an R² score of 0.9926 and an RMSE of 2.1278.
*   The Adult Enrollment Model achieved an R² score of 0.9984 and an RMSE of 1.1578.
*   The `SAVING MODELS FOR WEB DEPLOYMENT` cell was re-executed, successfully saving `le_state` to `models/label_encoder_state.pkl` and `le_district` to `models/label_encoder_district.pkl`, ensuring they are available for web deployment.

### Insights or Next Steps

*   Using separate `LabelEncoder` instances for distinct categorical features like 'state' and 'district' enhances data integrity and prevents potential encoding conflicts, making the model more robust to future data variations.
*   The successful saving of these distinct encoders ensures that the deployed models will correctly handle new input data by using the precise mappings learned during training for 'state' and 'district'.

"""